Avereha/tracing (#263)
What issue is this change attempting to solve?

Add support for sending traces in Jaeger format from carbonzipper and carbonapi.
Carbonapi is also able to read b3 trace headers that come from grafana.
How does this change solve the problem? Why is this the best approach?

I'm using this new dependency to send traces:

https://github.com/open-telemetry/opentelemetry-go
and
https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/instrumentation/github.com/gorilla/mux
for hooking up to gorilla mux.

Since we don't use gorilla mux yet, information in traces is missing route information, for example:

 HTTP POST route not found

but this should be fixed after #207

Also updated golang version in the travis tests to 1.14 to fix:

vendor/go.opentelemetry.io/otel/api/standard/http.go:242:25: undefined: http.StatusEarlyHints

How can we be sure this works as expected?

I ran multiple tests:

    tested that we can send traces to opentelemetry-collector and that we are receiving them on the other side.
    tested on one production server, there was no change in performance:
        with tracing disabled
        with tracing enabled
            when the collector is working
            when the collector is not responding/timing out